version: '3'

networks:
  bridge_network:
    name: lite_monitor
services:
  db:
    container_name: lite_monitor_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: lite-monitor
      MONGO_INITDB_DATABASE: lite_monitor
    image: mongo:latest
    networks:
      - bridge_network
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
